name = "pgshims"
main = "dist/cfworker/index.js"
compatibility_date = "2022-10-19"
node_compat = false

[build]
watch_dir = "src"
command = "./build.sh"

[vars]
# DATABASE_URL
# Run `wrangler secret put DATABASE_URL` and enter the connection string when prompted.
# And/or for local dev, create `.dev.vars` containing `DATABASE_URL=postgres://mysecretconnstr`.
